[package]
name = "aabb-rust"
version = "0.1.0"
authors = ["Pontus Alexander <pontus.alexander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"
rand = "0.7.3"
